cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('add/', views.AddBookToCart.as_view(), name='cart_update'),
    path('delete/<int:pk>', views.BookInCartDelete.as_view(), name='book_in_cart_delete'),
    path('', views.CartView.as_view(), name='cart_view')
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from books.views import BookListView, BookView, CreateBook, DeleteBookView, UpdateBook, BookSearch

from references import views
from home_screen.views import TopBooksListView
from my_auth.views import MyLogInView, MyLogOutView, MyPasswordChangeDoneView, MyPasswordChangeView, SignUpView
from cart import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', BookListView.as_view()),
    path('book/search/', BookSearch.as_view(), name='search'),
    path('signin/', MyLogInView.as_view(), name="login"),
    path('logout/', MyLogOutView.as_view(), name='logout'),
    path('password_change/', MyPasswordChangeView.as_view(),
         name='password_change'),
    path('password_change_done/', MyPasswordChangeDoneView.as_view(),
         name='password_change_done'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('profile/', include('my_profile.urls', namespace='profile')),
    path('order/', include('order.urls', namespace='order')),
    path('s_admin/', include('s_admin.urls', namespace='s_admin')),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('book/<int:pk>/', BookView.as_view()),
    path('book/create', CreateBook.as_view()),
    path('book/<int:pk>/update', UpdateBook.as_view()),
    path('book/<int:pk>/delete', DeleteBookView.as_view()),
    path('genre/', views.GenreListView.as_view()),
    path('genre/<int:pk>/', views.GenreView.as_view()),
    path('author/', views.AuthorListView.as_view()),
    path('author/<int:pk>/', views.AuthorView.as_view()),
    path('publishing_house/', views.PublishingHouseListView.as_view()),
    path('publishing_house/<int:pk>/', views.PublishingHouseView.as_view()),
    path('series/', views.SeriesListView.as_view()),
    path('series/<int:pk>/', views.SeriesView.as_view()),
    path('genre/create/', views.CreateGenre.as_view()),
    path('author/create', views.CreateAuthor.as_view()),
    path('series/create', views.CreateSeries.as_view()),
    path('publishing_house/create', views.CreatePublishingHouse.as_view()),
    path('genre/<int:pk>/update', views.UpdateGenre.as_view()),
    path('author/<int:pk>/update', views.UpdateAuthor.as_view()),
    path('series/<int:pk>/update', views.UpdateSeries.as_view()),
    path('publishing_house/<int:pk>/update', views.UpdatePublishingHouse.as_view()),
    path('genre/<int:pk>/delete', views.DeleteGenreView.as_view()),
    path('author/<int:pk>/delete', views.DeleteAuthorView.as_view()),
    path('series/<int:pk>/delete', views.DeleteSeriesView.as_view()),
    path('publishing_house/<int:pk>/delete', views.DeletePublishingHouseView.as_view()),
    path('', TopBooksListView.as_view())
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from references.models import *
from datetime import date


class Book(models.Model):
    name = models.CharField(
        "Title",
        max_length=100,
        blank=False,
        null=False
    )

    cover_photo = models.ImageField(
        "Cover",
        default='',
        upload_to='media/'
    )

    author = models.ManyToManyField(
        Author
    )

    genre = models.ManyToManyField(
        Genre
    )

    series = models.ForeignKey(
        Series,
        default=1,
        on_delete=models.CASCADE
    )

    publishing_house = models.ForeignKey(
        PublishingHouse,
        default=1,
        on_delete=models.CASCADE
    )

    price = models.DecimalField(
        "Price in BYN",
        default=0.0,
        max_digits=10,
        decimal_places=2,
        blank=False,
        null=False
    )

    FORMAT_CHOICES = (('84×108/16', '84×108/16'), ('70×90/8', '70×90/8'), ('70×90/16', '70×90/16'),
                      ('75×90/16', '75×90/16'), ('60×90/16', '60×90/16'), ('84×108/32', '84×108/32'),
                      ('70×90/32', '70×90/32'), ('70×108/32', '70×108/32'), ('60×90/32', '60×90/32'))
    format = models.CharField(
        "Format",
        max_length=15,
        default=1,
        choices=FORMAT_CHOICES,
        blank=False,
        null=False
    )

    isbn_code = models.CharField(
        "ISBN",
        default='',
        max_length=20,
        blank=False,
        null=False
    )

    publishing_date = models.DateField(
        "Date of publishing",
        default=date.today,
        blank=False,
        null=False
    )

    pages_amount = models.PositiveIntegerField(
        "Amount of pages",
        default=0,
        blank=False,
        null=False
    )

    binding = models.CharField(
        "Binding",
        default="",
        max_length=50,
        blank=False,
        null=False
    )

    weight = models.PositiveIntegerField(
        "Weight (g)",
        default=0,
        blank=False,
        null=False
    )

    books_amount = models.PositiveIntegerField(
        "Left amount",
        default=0,
        blank=False,
        null=False
    )

    AGE_LIMIT_CHOICES = (('18+', '18+'), ('16+', '16+'), ('14+', '14+'),
                         ('12+', '12+'), ('10+', '10+'), ('8+', '8+'),
                         ('6+', '6+'), ('3+', '3+'), ('0+', '0+'))
    age_limit = models.CharField(
        "Age limit",
        max_length=4,
        default=1,
        choices=AGE_LIMIT_CHOICES,
        blank=False,
        null=False
    )

    CHOICES = (('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'),
               ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'),
               ('8', '8'), ('9', '9'), ('10', '10'))
    rating = models.CharField(
        "Rating",
        max_length=10,
        default=0,
        choices=CHOICES,
        blank=False,
        null=False
    )

    BOOL_CHOICES = (('Yes', 'Yes'), ('No', 'No'))
    is_active = models.CharField(
        "Is active?",
        choices=BOOL_CHOICES,
        max_length=3,
        default=True,
        blank=False,
        null=False
    )

    entry_date = models.DateTimeField(
        "Date of entry",
        auto_now_add=True,
        null=True,
        blank=True
    )

    update_date = models.DateTimeField(
        "Date of updating",
        auto_now=True,
        null=True,
        blank=True
    )

    def __str__(self):
        return self.name

references/models.py
from django.db import models


class Author(models.Model):
    author = models.CharField(
        "Author",
        max_length=30,
        blank=False,
        null=False
    )

    biography = models.TextField(
        "About author",
        max_length=500,
        blank=True,
        null=True
    )

    def __str__(self):
        return self.author


class Series(models.Model):
    title = models.CharField(
        "Title of series",
        max_length=100,
        blank=False,
        null=False
    )

    description = models.TextField(
        "About this series",
        max_length=500,
        blank=True,
        null=True
    )

    def __str__(self):
        return self.title


class Genre(models.Model):
    genre = models.CharField(
        "Genre",
        max_length=50,
        blank=False,
        null=False
    )

    description = models.TextField(
        "About this genre",
        max_length=500,
        blank=True,
        null=True
    )

    def __str__(self):
        return self.genre


class PublishingHouse(models.Model):
    house = models.CharField(
        "Publishing House",
        max_length=40,
        blank=False,
        null=False

    )

    history = models.TextField(
        "Other books of this house",
        max_length=500,
        blank=True,
        null=True
    )

    def __str__(self):
        return self.house

books/forms.py
from django import forms
from . import models


class BookForm(forms.ModelForm):
    class Meta:
        model = models.Book
        fields = '__all__'


class CreateBook(forms.ModelForm):
    class Meta:
        model = models.Book
        fields = '__all__'


class UpdateBook(forms.ModelForm):
    class Meta:
        model = models.Book
        fields = '__all__'

references/forms.py
from django import forms
from . import models


class CreateGenre(forms.ModelForm):
    class Meta:
        model = models.Genre
        fields = (
            'genre',
            'description'
        )


class CreateAuthor(forms.ModelForm):
    class Meta:
        model = models.Author
        fields = (
            'author',
            'biography'
        )


class CreateSeries(forms.ModelForm):
    class Meta:
        model = models.Series
        fields = (
            'title',
            'description'
        )


class CreatePublishingHouse(forms.ModelForm):
    class Meta:
        model = models.PublishingHouse
        fields = (
            'house',
            'history'
        )


class UpdateGenre(forms.ModelForm):
    class Meta:
        model = models.Genre
        fields = (
            'genre',
            'description'
        )


class UpdateAuthor(forms.ModelForm):
    class Meta:
        model = models.Author
        fields = (
            'author',
            'biography'
        )


class UpdateSeries(forms.ModelForm):
    class Meta:
        model = models.Series
        fields = (
            'title',
            'description'
        )


class UpdatePublishingHouse(forms.ModelForm):
    class Meta:
        model = models.PublishingHouse
        fields = (
            'house',
            'history'
        )

books/views.py
from django.shortcuts import render
from books import forms, models
from django.views.generic import ListView, DetailView, DeleteView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q


class BookListView(ListView):
    paginate_by = 10
    template_name = 'books/book_list.html'
    model = models.Book


class BookView(DetailView):
    template_name = 'books/book_view.html'
    model = models.Book


class CreateBook(LoginRequiredMixin, CreateView):
    template_name = 'books/create_book.html'
    model = models.Book
    form_class = forms.CreateBook
    success_url = '/book'
    login_url = '/login'


class UpdateBook(LoginRequiredMixin, UpdateView):
    template_name = 'books/update_book.html'
    model = models.Book
    form_class = forms.UpdateBook
    success_url = '/book'
    login_url = '/login'


class DeleteBookView(LoginRequiredMixin, DeleteView):
    model = models.Book
    template_name = 'refs/delete_view.html'
    success_url = '/book'
    login_url = '/login'


class BookSearch(ListView):
    model = models.Book
    template_name = 'books/book_list.html'
    paginate_by = 10

    def get_queryset(self):
        search = self.request.GET.get('search')
        books = models.Book.objects.filter(Q(name__icontains=search))
        return books

references/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic import ListView, DetailView, DeleteView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from references import models
from references import forms


class GenreListView(ListView):
    template_name = 'refs/genre_list_view.html'
    model = models.Genre
    paginate_by = 10


class AuthorListView(ListView):
    template_name = 'refs/author_list_view.html'
    model = models.Author
    paginate_by = 10


class PublishingHouseListView(ListView):
    template_name = 'refs/publishing_house_list_view.html'
    model = models.PublishingHouse
    paginate_by = 10


class SeriesListView(ListView):
    template_name = 'refs/series_list_view.html'
    model = models.Series
    paginate_by = 10


class GenreView(DetailView):
    template_name = 'refs/genre_view.html'
    model = models.Genre


class AuthorView(DetailView):
    template_name = 'refs/author_view.html'
    model = models.Author


class PublishingHouseView(DetailView):
    template_name = 'refs/publishing_house_view.html'
    model = models.PublishingHouse


class SeriesView(DetailView):
    template_name = 'refs/series_view.html'
    model = models.Series


class CreateGenre(LoginRequiredMixin, CreateView):
    template_name = 'refs/create_genre.html'
    model = models.Genre
    form_class = forms.CreateGenre
    success_url = '/genre'
    login_url = reverse_lazy('login')


class CreateAuthor(LoginRequiredMixin, CreateView):
    template_name = 'refs/create_author.html'
    model = models.Author
    form_class = forms.CreateAuthor
    success_url = '/author'
    login_url = reverse_lazy('login')


class CreatePublishingHouse(LoginRequiredMixin, CreateView):
    template_name = 'refs/create_publishing_house.html'
    model = models.PublishingHouse
    form_class = forms.CreatePublishingHouse
    success_url = '/publishing_house'
    login_url = reverse_lazy('login')


class CreateSeries(LoginRequiredMixin, CreateView):
    template_name = 'refs/create_series.html'
    model = models.Series
    form_class = forms.CreateSeries
    success_url = '/series'
    login_url = reverse_lazy('login')


class UpdateGenre(LoginRequiredMixin, UpdateView):
    template_name = 'refs/update_genre.html'
    model = models.Genre
    form_class = forms.UpdateGenre
    success_url = '/genre'
    login_url = reverse_lazy('login')


class UpdateAuthor(LoginRequiredMixin, UpdateView):
    template_name = 'refs/update_author.html'
    model = models.Author
    form_class = forms.UpdateAuthor
    success_url = '/author'
    login_url = reverse_lazy('login')


class UpdatePublishingHouse(LoginRequiredMixin, UpdateView):
    template_name = 'refs/update_publishing_house.html'
    model = models.PublishingHouse
    form_class = forms.UpdatePublishingHouse
    success_url = '/publishing_house'
    login_url = reverse_lazy('login')


class UpdateSeries(LoginRequiredMixin, UpdateView):
    template_name = 'refs/update_series.html'
    model = models.Series
    form_class = forms.UpdateSeries
    success_url = '/series'
    login_url = reverse_lazy('login')


def update_author(request, pk_obj):
    if request.method == "POST":
        form = forms.UpdateAuthor(data=request.POST)
        if form.is_valid():
            author = form.cleaned_data.get('author')
            biography = form.cleaned_data.get('biography')
            new_author = models.Author.objects.get(pk=pk_obj)
            new_author.author = author
            new_author.biography = biography
            new_author.save()
            return HttpResponseRedirect(f'/author/{pk_obj}')
    else:
        author = models.Author.objects.get(pk=pk_obj)
        form = forms.UpdateAuthor(data={'author': author.author, 'biography': author.biography})
        return render(request, template_name='refs/update_author.html', context={'form': form})


def update_series(request, pk_obj):
    if request.method == "POST":
        form = forms.UpdateSeries(data=request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            description = form.cleaned_data.get('description')
            new_title = models.Series.objects.get(pk=pk_obj)
            new_title.title = title
            new_title.description = description
            new_title.save()
            return HttpResponseRedirect(f'/series/{pk_obj}')
    else:
        title = models.Series.objects.get(pk=pk_obj)
        form = forms.UpdateSeries(data={'title': title.title, 'description': title.description})
        return render(request, template_name='refs/update_series.html', context={'form': form})


def update_publishing_house(request, pk_obj):
    if request.method == "POST":
        form = forms.UpdatePublishingHouse(data=request.POST)
        if form.is_valid():
            house = form.cleaned_data.get('house')
            history = form.cleaned_data.get('history')
            new_house = models.PublishingHouse.objects.get(pk=pk_obj)
            new_house.house = house
            new_house.history = history
            new_house.save()
            return HttpResponseRedirect(f'/publishing_house/{pk_obj}')
    else:
        house = models.PublishingHouse.objects.get(pk=pk_obj)
        form = forms.UpdatePublishingHouse(data={'house': house.house, 'history': house.history})
        return render(request, template_name='refs/update_publishing_house.html', context={'form': form})


class DeleteGenreView(LoginRequiredMixin, DeleteView):
    model = models.Genre
    template_name = 'refs/delete_view.html'
    success_url = '/genre'
    login_url = reverse_lazy('login')


class DeleteAuthorView(LoginRequiredMixin, DeleteView):
    model = models.Author
    template_name = 'refs/delete_view.html'
    success_url = '/author'
    login_url = reverse_lazy('login')


class DeletePublishingHouseView(LoginRequiredMixin, DeleteView):
    model = models.PublishingHouse
    template_name = 'refs/delete_view.html'
    success_url = '/publishing_house'
    login_url = reverse_lazy('login')


class DeleteSeriesView(LoginRequiredMixin, DeleteView):
    model = models.Series
    template_name = 'refs/delete_view.html'
    success_url = '/series'
    login_url = reverse_lazy('login')

references/templates/books/book_list.html
{% extends 'customer_base.html' %}
{% load static %}
{% load crispy_forms_filters %}


{% block title %}
    <title>Home Page</title>
{% endblock title %}

{% block body %}
    <h1>Books</h1>
    {% include 'paginator.html' %}
    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">Title</th>
            <th scope="col">Price</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>

        {% for book in object_list %}

            <tr>

                <td>{{ book.name }}</td>

                <td>{{ book.price }}</td>
                <td>
                    <a href="/book/{{ book.pk }}" class="btn btn-info">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-eye" fill="currentColor"
                             xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                  d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.134 13.134 0 0 0 1.66 2.043C4.12 11.332 5.88 12.5 8 12.5c2.12 0 3.879-1.168 5.168-2.457A13.134 13.134 0 0 0 14.828 8a13.133 13.133 0 0 0-1.66-2.043C11.879 4.668 10.119 3.5 8 3.5c-2.12 0-3.879 1.168-5.168 2.457A13.133 13.133 0 0 0 1.172 8z"/>
                            <path fill-rule="evenodd"
                                  d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
                        </svg>
                    </a>
                        <a href="{% url 'cart:cart_update' %}?book={{ book.pk }}" class="btn btn-success">
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-cart" fill="currentColor"
                                 xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd"
                                      d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm7 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
                            </svg>
                        </a>
                </td>
            </tr>

        {% endfor %}


    </table>
{% endblock body %}

references/templates/books/book_view.html
{% extends 'customer_base.html' %}
{% load static %}
{% block title %}
    <title>Home Page</title>
{% endblock title %}

{% block body %}

    <h1>{{ book.name }}</h1>
    <b>Title</b> - {{ book.name }}<br>
    <b>Cover</b> - <img src="{{ book.cover_photo.url }}" alt="Cover photo" width="100" height="100"><br>
    <b>Author</b> -
    {% for author in book.author.all %}
        {{ author }}<br>
    {% endfor %}
    <b>Series</b> - {{ book.series.title }}<br>
    <b>Publishing House</b> - {{ book.publishing_house.house }}<br>
    <b>Genre</b> -
    {% for genre in book.genre.all %}
        {{ genre }}<br>
    {% endfor %}
    <b>Price</b> - {{ book.price }}<br>
    <b>Format</b> - {{ book.format }}<br>
    <b>ISBN</b> - {{ book.isbn_code }}<br>
    <b>Publishing Date</b> - {{ book.publishing_date }}<br>
    <b>Pages Amount</b> - {{ book.pages_amount }}<br>
    <b>Binding</b> - {{ book.binding }}<br>
    <b>Weight</b> - {{ book.weight }}<br>
    <b>Amount</b> - {{ book.books_amount }}<br>
    <b>Age limit</b> - {{ book.age_limit }}<br>
    <b>Rating</b> - {{ book.rating }}<br>
    <b>Active</b> - {{ book.is_active }}<br>

{% endblock body %}

references/templates/books/create_book.html
{% extends 'customer_base.html' %}
{% load crispy_forms_filters %}

{% block title %}
<title>Create Book</title>
{% endblock title %}

{% block body %}
<h1>Create Book</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-secondary">Create</button>
</form>
{% endblock body %}

references/templates/books/update_book.html
{% extends 'customer_base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Update Book</title>
{% endblock title %}

{% block body %}
    <h1>Update Book</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-secondary">Update</button>
    </form>
{% endblock body %}