cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('add/', views.AddBookToCart.as_view(), name='cart_update'),
    path('delete/<int:pk>', views.BookInCartDelete.as_view(), name='book_in_cart_delete'),
    path('', views.CartView.as_view(), name='cart_view')
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'
urlpatterns = [
    path('create/', views.CreateOrder.as_view(), name='create_order'),
    path('update/<int:pk>/', views.CancelOrder.as_view(), name='update_order'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from books.views import BookListView, BookView, CreateBook, DeleteBookView, UpdateBook, BookSearch

from references import views
from home_screen.views import TopBooksListView
from my_auth.views import MyLogInView, MyLogOutView, MyPasswordChangeDoneView, MyPasswordChangeView, SignUpView
from cart import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', BookListView.as_view()),
    path('book/search/', BookSearch.as_view(), name='search'),
    path('signin/', MyLogInView.as_view(), name="login"),
    path('logout/', MyLogOutView.as_view(), name='logout'),
    path('password_change/', MyPasswordChangeView.as_view(),
         name='password_change'),
    path('password_change_done/', MyPasswordChangeDoneView.as_view(),
         name='password_change_done'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('profile/', include('my_profile.urls', namespace='profile')),
    path('order/', include('order.urls', namespace='order')),
    path('s_admin/', include('s_admin.urls', namespace='s_admin')),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('book/<int:pk>/', BookView.as_view()),
    path('book/create', CreateBook.as_view()),
    path('book/<int:pk>/update', UpdateBook.as_view()),
    path('book/<int:pk>/delete', DeleteBookView.as_view()),
    path('genre/', views.GenreListView.as_view()),
    path('genre/<int:pk>/', views.GenreView.as_view()),
    path('author/', views.AuthorListView.as_view()),
    path('author/<int:pk>/', views.AuthorView.as_view()),
    path('publishing_house/', views.PublishingHouseListView.as_view()),
    path('publishing_house/<int:pk>/', views.PublishingHouseView.as_view()),
    path('series/', views.SeriesListView.as_view()),
    path('series/<int:pk>/', views.SeriesView.as_view()),
    path('genre/create/', views.CreateGenre.as_view()),
    path('author/create', views.CreateAuthor.as_view()),
    path('series/create', views.CreateSeries.as_view()),
    path('publishing_house/create', views.CreatePublishingHouse.as_view()),
    path('genre/<int:pk>/update', views.UpdateGenre.as_view()),
    path('author/<int:pk>/update', views.UpdateAuthor.as_view()),
    path('series/<int:pk>/update', views.UpdateSeries.as_view()),
    path('publishing_house/<int:pk>/update', views.UpdatePublishingHouse.as_view()),
    path('genre/<int:pk>/delete', views.DeleteGenreView.as_view()),
    path('author/<int:pk>/delete', views.DeleteAuthorView.as_view()),
    path('series/<int:pk>/delete', views.DeleteSeriesView.as_view()),
    path('publishing_house/<int:pk>/delete', views.DeletePublishingHouseView.as_view()),
    path('', TopBooksListView.as_view())
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from django.contrib.auth import get_user_model
from books.models import Book

User = get_user_model()


class Cart(models.Model):
    customer = models.ForeignKey(
        User,
        related_name='templates',
        on_delete=models.PROTECT,
        blank=True,
        null=True
    )

    created_date = models.DateTimeField(
        "Created Date",
        auto_now_add=True,
        null=True,
        blank=True
    )

    updated_date = models.DateTimeField(
        "Updated Date",
        auto_now=True,
        null=True,
        blank=True
    )

    def total_price(self):
        price = 0
        for book in self.books.all():
            price += book.price
        return price


class BookInCart(models.Model):
    cart = models.ForeignKey(
        Cart,
        on_delete=models.CASCADE,
        related_name='books'
    )

    book = models.ForeignKey(
        Book,
        on_delete=models.PROTECT,
        related_name='book_in_cart',
        default=1
    )

    quantity = models.IntegerField(
        'Quantity',
        default=1
    )

    price = models.DecimalField(
        'Price',
        max_digits=10,
        decimal_places=2,
    )

    def book_total_price(self):
        return self.quantity * self.book.price

    def __str__(self):
        return f"{self.book} in the cart for {self.cart.customer}"

cart/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, DeleteView
from django.urls import reverse_lazy
from . import models
from books import models as book_models


class CartView(TemplateView):
    template_name = 'cart/add_to_cart.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_id = self.request.session.get('cart_id')
        user = self.request.user
        if not isinstance(user, models.User):
            user = None

        if cart_id:
            cart = models.Cart.objects.filter(pk=cart_id).first()
            if not cart:
                cart = models.Cart.objects.create(customer=user)
                self.request.session['cart_id'] = cart.pk
        else:
            cart = models.Cart.objects.create(customer=user)
            self.request.session['cart_id'] = cart.pk

        context['cart'] = cart
        return context


class AddBookToCart(TemplateView):
    template_name = 'cart/cart.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_id = self.request.session.get('cart_id')
        user = self.request.user
        if not isinstance(user, models.User):
            user = None

        if cart_id:
            cart = models.Cart.objects.filter(pk=cart_id).first()
            if not cart:
                cart = models.Cart.objects.create(customer=user)
                self.request.session['cart_id'] = cart.pk
        else:
            cart = models.Cart.objects.create(customer=user)
            self.request.session['cart_id'] = cart.pk

        book_id = self.request.GET.get('book')
        book = book_models.Book.objects.filter(pk=book_id).first()

        if book:
            book_in_cart, created = models.BookInCart.objects.get_or_create(
                book=book,
                cart=cart,
                defaults={
                    'quantity': 1,
                    'price': book.price
                }
            )

            if not created:
                book_in_cart.quantity += 1
                book_in_cart.price = book_in_cart.book_total_price()
                book_in_cart.save()

        context['cart'] = cart
        context['book'] = book

        return context


class BookInCartDelete(DeleteView):
    template_name = 'refs/delete_view.html'
    model = models.BookInCart
    success_url = reverse_lazy('cart:cart_update')

cart/templates/cart/add_to_cart.html
{% extends 'customer_base.html' %}
{% block title %}
    <title>Cart</title>
{% endblock title %}

{% block body %}
    {% if not user %}
        <h4>Guest</h4>
    {% else %}
        <h4>{{ user.username|title }}</h4>
    {% endif %}
    <table class="table">

        <thead>
        <tr>
            <th scope="col">Photo</th>
            <th scope="col">Title</th>
            <th scope="col">Quantity</th>
            <th scope="col">Price</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        {% for book_in_cart in cart.books.all %}
            <tr>
                <td><img src="{{ book_in_cart.book.cover_photo.url }}" class="mr-3" alt="..." width="64" height="64">
                </td>
                <td>{{ book_in_cart.book.name }}</td>
                <td>{{ book_in_cart.quantity }}</td>
                <td>{{ book_in_cart.price }}</td>
                <td>
                    <a href="{% url 'cart:book_in_cart_delete' book_in_cart.pk %}" class="btn btn-danger">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor"
                             xmlns="http://www.w3.org/2000/svg">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                            <path fill-rule="evenodd"
                                  d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                        </svg>
                    </a></td>
            </tr>
        {% endfor %}
    </table>

    <h6>Total price: {{ cart.total_price }}</h6>
    <a href='{% url 'order:create_order' %}' class="btn btn-secondary" type="submit">Order</a>

{% endblock body %}

cart/templates/cart/cart.html
{% extends 'customer_base.html' %}
{% block title %}
    <title>Cart</title>
{% endblock title %}

{% block body %}
    {% if not user %}
        <h4>Guest</h4>
    {% else %}
        <h4>{{ user.username|title }}</h4>
    {% endif %}
        <table class="table">

        <thead>
        <tr>
            <th scope="col">Photo</th>
            <th scope="col">Title</th>
            <th scope="col">Quantity</th>
            <th scope="col">Price</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        {% for book_in_cart in cart.books.all %}
            <tr>
                <td><img src="{{ book_in_cart.book.cover_photo.url }}" class="mr-3" alt="..." width="64" height="64"></td>
                <td>{{ book_in_cart.book.name }}</td>
                <td>{{ book_in_cart.quantity }}</td>
                <td>{{ book_in_cart.price }}</td>
                <td>
                    <a href="{% url 'cart:book_in_cart_delete' book_in_cart.pk%}" class="btn btn-danger">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor"
                             xmlns="http://www.w3.org/2000/svg">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                            <path fill-rule="evenodd"
                                  d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                        </svg>
                    </a></td>
            </tr>
        {% endfor %}
    </table>

    <h6>Total price: {{ cart.total_price }}</h6>
    <a href='{% url 'order:create_order'%}' class="btn btn-secondary" type="submit">Order</a>

{% endblock body %}