cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('add/', views.AddBookToCart.as_view(), name='cart_update'),
    path('delete/<int:pk>', views.BookInCartDelete.as_view(), name='book_in_cart_delete'),
    path('', views.CartView.as_view(), name='cart_view')
]

s_admin/urls.py
from django.urls import path
from s_admin import views

app_name = 's_admin'

urlpatterns = [
    path('order/list/', views.SAdminOrderList.as_view(), name='s_admin_order_list'),
    path('order/update/<int:pk>/', views.SAdminOrderUpdate.as_view(), name='s_admin_order_update'),
    path('order/delete/<int:pk>/', views.SAdminOrderDelete.as_view(), name='s_admin_order_delete'),

    path('genre/list/', views.SAdminGenreList.as_view(), name='s_admin_genre_list'),
    path('genre/create/', views.SAdminGenreCreate.as_view(), name='s_admin_genre_create'),
    path('genre/view/<int:pk>/', views.SAdminGenreView.as_view(), name='s_admin_genre_view'),
    path('genre/update/<int:pk>/', views.SAdminGenreUpdate.as_view(), name='s_admin_genre_update'),
    path('genre/delete/<int:pk>/', views.SAdminGenreDelete.as_view(), name='s_admin_genre_delete'),

    path('series/list/', views.SAdminSeriesList.as_view(), name='s_admin_series_list'),
    path('series/create/', views.SAdminSeriesCreate.as_view(), name='s_admin_series_create'),
    path('series/view/<int:pk>/', views.SAdminSeriesView.as_view(), name='s_admin_series_view'),
    path('series/update/<int:pk>/', views.SAdminSeriesUpdate.as_view(), name='s_admin_series_update'),
    path('series/delete/<int:pk>/', views.SAdminSeriesDelete.as_view(), name='s_admin_series_delete'),

    path('author/list/', views.SAdminAuthorList.as_view(), name='s_admin_author_list'),
    path('author/create/', views.SAdminAuthorCreate.as_view(), name='s_admin_author_create'),
    path('author/view/<int:pk>/', views.SAdminAuthorView.as_view(), name='s_admin_author_view'),
    path('author/delete/<int:pk>/', views.SAdminAuthorDelete.as_view(), name='s_admin_author_delete'),
    path('author/update/<int:pk>/', views.SAdminAuthorUpdate.as_view(), name='s_admin_author_update'),

    path('publishing_house/list/', views.SAdminPublishingHouseList.as_view(), name='s_admin_publishing_house_list'),
    path('publishing_house/create/', views.SAdminPublishingHouseCreate.as_view(),
         name='s_admin_publishing_house_create'),
    path('publishing_house/view/<int:pk>/', views.SAdminPublishingHouseView.as_view(),
         name='s_admin_publishing_house_view'),
    path('publishing_house/update/<int:pk>/', views.SAdminPublishingHouseUpdate.as_view(),
         name='s_admin_publishing_house_update'),
    path('publishing_house/delete/<int:pk>/', views.SAdminPublishingHouseDelete.as_view(),
         name='s_admin_publishing_house_delete'),

    path('book/list/', views.SAdminBookList.as_view(), name='s_admin_book_list'),
    path('book/create/', views.SAdminBookCreate.as_view(), name='s_admin_book_create'),
    path('book/delete/<int:pk>/', views.SAdminBookDelete.as_view(), name='s_admin_book_delete'),
    path('book/update/<int:pk>/', views.SAdminBookUpdate.as_view(), name='s_admin_book_update'),
    path('book/view/<int:pk>/', views.SAdminBookView.as_view(), name='s_admin_book_view'),

    path('customer/list/', views.CustomersList.as_view(), name='s_admin_customer_list'),
    path('customer/update/<int:pk>/', views.CustomerUpdate.as_view(), name='s_admin_customer_update'),
    path('customer/view/<int:pk>/', views.CustomerView.as_view(), name='s_admin_customer_view'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from books.views import BookListView, BookView, CreateBook, DeleteBookView, UpdateBook, BookSearch

from references import views
from home_screen.views import TopBooksListView
from my_auth.views import MyLogInView, MyLogOutView, MyPasswordChangeDoneView, MyPasswordChangeView, SignUpView
from cart import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', BookListView.as_view()),
    path('book/search/', BookSearch.as_view(), name='search'),
    path('signin/', MyLogInView.as_view(), name="login"),
    path('logout/', MyLogOutView.as_view(), name='logout'),
    path('password_change/', MyPasswordChangeView.as_view(),
         name='password_change'),
    path('password_change_done/', MyPasswordChangeDoneView.as_view(),
         name='password_change_done'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('profile/', include('my_profile.urls', namespace='profile')),
    path('order/', include('order.urls', namespace='order')),
    path('s_admin/', include('s_admin.urls', namespace='s_admin')),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('book/<int:pk>/', BookView.as_view()),
    path('book/create', CreateBook.as_view()),
    path('book/<int:pk>/update', UpdateBook.as_view()),
    path('book/<int:pk>/delete', DeleteBookView.as_view()),
    path('genre/', views.GenreListView.as_view()),
    path('genre/<int:pk>/', views.GenreView.as_view()),
    path('author/', views.AuthorListView.as_view()),
    path('author/<int:pk>/', views.AuthorView.as_view()),
    path('publishing_house/', views.PublishingHouseListView.as_view()),
    path('publishing_house/<int:pk>/', views.PublishingHouseView.as_view()),
    path('series/', views.SeriesListView.as_view()),
    path('series/<int:pk>/', views.SeriesView.as_view()),
    path('genre/create/', views.CreateGenre.as_view()),
    path('author/create', views.CreateAuthor.as_view()),
    path('series/create', views.CreateSeries.as_view()),
    path('publishing_house/create', views.CreatePublishingHouse.as_view()),
    path('genre/<int:pk>/update', views.UpdateGenre.as_view()),
    path('author/<int:pk>/update', views.UpdateAuthor.as_view()),
    path('series/<int:pk>/update', views.UpdateSeries.as_view()),
    path('publishing_house/<int:pk>/update', views.UpdatePublishingHouse.as_view()),
    path('genre/<int:pk>/delete', views.DeleteGenreView.as_view()),
    path('author/<int:pk>/delete', views.DeleteAuthorView.as_view()),
    path('series/<int:pk>/delete', views.DeleteSeriesView.as_view()),
    path('publishing_house/<int:pk>/delete', views.DeletePublishingHouseView.as_view()),
    path('', TopBooksListView.as_view())
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

s_admin/models.py
from django.db import models

# Create your models here.

books/views.py
from django.shortcuts import render
from books import forms, models
from django.views.generic import ListView, DetailView, DeleteView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q


class BookListView(ListView):
    paginate_by = 10
    template_name = 'books/book_list.html'
    model = models.Book


class BookView(DetailView):
    template_name = 'books/book_view.html'
    model = models.Book


class CreateBook(LoginRequiredMixin, CreateView):
    template_name = 'books/create_book.html'
    model = models.Book
    form_class = forms.CreateBook
    success_url = '/book'
    login_url = '/login'


class UpdateBook(LoginRequiredMixin, UpdateView):
    template_name = 'books/update_book.html'
    model = models.Book
    form_class = forms.UpdateBook
    success_url = '/book'
    login_url = '/login'


class DeleteBookView(LoginRequiredMixin, DeleteView):
    model = models.Book
    template_name = 'refs/delete_view.html'
    success_url = '/book'
    login_url = '/login'


class BookSearch(ListView):
    model = models.Book
    template_name = 'books/book_list.html'
    paginate_by = 10

    def get_queryset(self):
        search = self.request.GET.get('search')
        books = models.Book.objects.filter(Q(name__icontains=search))
        return books

s_admin/views.py
from django.shortcuts import render

from books import views as book_view

from order.models import Order

from references import models as ref_models

from my_profile.models import Profile
from my_profile import views as my_profile_views

from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy


class SAdminOrderList(LoginRequiredMixin, ListView):
    model = Order
    template_name = 's_admin/order/s_admin_order_list.html'
    success_url = reverse_lazy('s_admin:s_admin_order_list')

    def get_queryset(self):
        if self.request.user.groups.filter(name='Customer'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all()


class SAdminOrderUpdate(LoginRequiredMixin, UpdateView):
    model = Order
    template_name = 's_admin/order/s_admin_order_update.html'
    fields = ('status1', 'status2', 'delivery_address', 'contact_phone', 'comment')
    success_url = reverse_lazy('s_admin:s_admin_order_list')

    def get_queryset(self):
        if self.request.user.groups.filter(name='Customer'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all()


class SAdminOrderDelete(LoginRequiredMixin, DeleteView):
    model = Order
    template_name = 's_admin/order/s_admin_order_delete.html'
    success_url = reverse_lazy('s_admin:s_admin_order_list')

    def get_queryset(self):
        if self.request.user.groups.filter(name='Customer'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all()


class SAdminGenreList(LoginRequiredMixin, ListView):
    model = ref_models.Genre
    template_name = 's_admin/genre/s_admin_genre_list.html'

    def get_queryset(self):
        if self.request.user.groups.filter(name='Customer'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all()


class SAdminGenreCreate(LoginRequiredMixin, CreateView):
    model = ref_models.Genre
    fields = '__all__'
    success_url = reverse_lazy('s_admin:s_admin_genre_list')
    template_name = 's_admin/genre/s_admin_genre_create.html'

    def get_queryset(self):
        if self.request.user.groups.filter(name='Customer'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all()


class SAdminGenreUpdate(LoginRequiredMixin, UpdateView):
    model = ref_models.Genre
    fields = '__all__'
    success_url = reverse_lazy('s_admin:s_admin_genre_list')
    template_name = 's_admin/genre/s_admin_genre_update.html'

    def get_queryset(self):
        if self.request.user.groups.filter(name='Customer'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all()


class SAdminGenreDelete(LoginRequiredMixin, DeleteView):
    model = ref_models.Genre
    success_url = reverse_lazy('s_admin:s_admin_genre_list')
    template_name = 's_admin/genre/s_admin_genre_delete.html'

    def get_queryset(self):
        if self.request.user.groups.filter(name='Customer'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all()


class SAdminGenreView(LoginRequiredMixin, DetailView):
    model = ref_models.Genre
    template_name = 's_admin/genre/s_admin_genre_view.html'

    def get_queryset(self):
        if self.request.user.groups.filter(name='Customer'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all()


class SAdminSeriesList(LoginRequiredMixin, ListView):
    model = ref_models.Series
    template_name = 's_admin/series/s_admin_series_list_view.html'

    def get_queryset(self):
        if self.request.user.groups.filter(name='Customer'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all()


class SAdminSeriesUpdate(LoginRequiredMixin, UpdateView):
    model = ref_models.Series
    fields = '__all__'
    success_url = reverse_lazy('s_admin:s_admin_series_list')
    template_name = 's_admin/series/s_admin_series_update.html'

    def get_queryset(self):
        if self.request.user.groups.filter(name='Customer'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all()


class SAdminSeriesDelete(LoginRequiredMixin, DeleteView):
    model = ref_models.Series
    success_url = reverse_lazy('s_admin:s_admin_series_list')
    template_name = 's_admin/series/s_admin_series_delete.html'

    def get_queryset(self):
        if self.request.user.groups.filter(name='Customer'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all()


class SAdminSeriesCreate(LoginRequiredMixin, CreateView):
    model = ref_models.Series
    fields = '__all__'
    success_url = reverse_lazy('s_admin:s_admin_series_list')
    template_name = 's_admin/series/s_admin_series_create.html'

    def get_queryset(self):
        if self.request.user.groups.filter(name='Customer'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all()


class SAdminSeriesView(LoginRequiredMixin, DetailView):
    model = ref_models.Series
    template_name = 's_admin/series/s_admin_series_view.html'

    def get_queryset(self):
        if self.request.user.groups.filter(name='Customer'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all()


class SAdminAuthorList(LoginRequiredMixin, ListView):
    model = ref_models.Author
    template_name = 's_admin/author/s_admin_author_list.html'

    def get_queryset(self):
        if self.request.user.groups.filter(name='Customer'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all()


class SAdminAuthorDelete(LoginRequiredMixin, DeleteView):
    model = ref_models.Author
    success_url = reverse_lazy('s_admin:s_admin_author_list')
    template_name = 's_admin/author/s_admin_author_delete.html'

    def get_queryset(self):
        if self.request.user.groups.filter(name='Customer'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all()


class SAdminAuthorUpdate(LoginRequiredMixin, UpdateView):
    model = ref_models.Author
    fields = '__all__'
    success_url = reverse_lazy('s_admin:s_admin_author_list')
    template_name = 's_admin/series/s_admin_series_update.html'

    def get_queryset(self):
        if self.request.user.groups.filter(name='Customer'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all()


class SAdminAuthorCreate(LoginRequiredMixin, CreateView):
    model = ref_models.Author
    fields = '__all__'
    success_url = reverse_lazy('s_admin:s_admin_author_list')
    template_name = 's_admin/author/s_admin_author_create.html'

    def get_queryset(self):
        if self.request.user.groups.filter(name='Customer'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all()


class SAdminAuthorView(LoginRequiredMixin, DetailView):
    model = ref_models.Author
    template_name = 's_admin/author/s_admin_author_view.html'

    def get_queryset(self):
        if self.request.user.groups.filter(name='Customer'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all()


class SAdminPublishingHouseList(LoginRequiredMixin, ListView):
    model = ref_models.PublishingHouse
    template_name = 's_admin/publishing_house/s_admin_publishing_house_list.html'

    def get_queryset(self):
        if self.request.user.groups.filter(name='Customer'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all()


class SAdminPublishingHouseView(LoginRequiredMixin, DetailView):
    model = ref_models.PublishingHouse
    template_name = 's_admin/publishing_house/s_admin_publishing_house_view.html'

    def get_queryset(self):
        if self.request.user.groups.filter(name='Customer'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all()


class SAdminPublishingHouseCreate(LoginRequiredMixin, CreateView):
    model = ref_models.PublishingHouse
    fields = '__all__'
    success_url = reverse_lazy('s_admin:s_admin_publishing_house_list')
    template_name = 's_admin/publishing_house/s_admin_publishing_house_create.html'

    def get_queryset(self):
        if self.request.user.groups.filter(name='Customer'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all()


class SAdminPublishingHouseUpdate(LoginRequiredMixin, UpdateView):
    model = ref_models.PublishingHouse
    fields = '__all__'
    success_url = reverse_lazy('s_admin:s_admin_publishing_house_list')
    template_name = 's_admin/publishing_house/s_admin_publishing_house_update.html'

    def get_queryset(self):
        if self.request.user.groups.filter(name='Customer'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all()


class SAdminPublishingHouseDelete(LoginRequiredMixin, DeleteView):
    model = ref_models.PublishingHouse
    success_url = reverse_lazy('s_admin:s_admin_publishing_house_list')
    template_name = 's_admin/publishing_house/s_admin_publishing_house_delete.html'

    def get_queryset(self):
        if self.request.user.groups.filter(name='Customer'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all()


class SAdminBookList(LoginRequiredMixin, book_view.BookListView):
    template_name = 's_admin/book/s_admin_book_list.html'
    paginate_by = 10

    def get_queryset(self):
        if self.request.user.groups.filter(name='Customer'):

s_admin/templates/s_admin/book/s_admin_book_create.html
{% extends "s_admin_base.html" %}
{% load crispy_forms_filters %}
  {% block title %}<title>Add new book</title>{% endblock title %}
{% block main %}
     <div class=container>
     <h3>Add new book</h3>
     <form  action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
            {{form|crispy}}
        <input class="btn btn-primary" type="submit" value="Create">
    <a class="btn btn-success" href="{% url 's_admin:s_admin_book_list' %}">Back </a>
    </form>
    </div>
    {% endblock main %}

s_admin/templates/s_admin/book/s_admin_book_delete.html
{% extends "s_admin_base.html" %}
{% load crispy_forms_filters %}
{% block title %}<title>Delete Book {{ object.name }} ???</title>{% endblock title %}

{% block main %}
    <body>
    <h1>Delete Book {{ object.name }} ?</h1>
    <form action="" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-secondary">Delete</button>
    </form>
{% endblock main %}

s_admin/templates/s_admin/book/s_admin_book_list.html
{% extends "s_admin_base.html" %}
{% block title %} <title>Genre List</title> {% endblock title %}

{% load crispy_forms_tags %}

{% block main %}
    <a class="btn btn-success" href="{% url 's_admin:s_admin_book_create' %}">Create</a>
    <table class="table table-striped">
        <thead class="thead-dark"></thead>
        <tr>
            <th>Book</th>
            <th>Price</th>
            <th>View</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
        {% for book in object_list %}
            <tr>
                <td>{{ book.name }}</td>
                <td>{{ book.price }}</td>
                <td><a class="btn badge-info" href="{% url 's_admin:s_admin_book_view' book.pk %}">View</a></td>
                <td><a class="btn badge-info" href="{% url 's_admin:s_admin_book_update' book.pk%}">Update</a></td>
                <td><a class="btn badge-danger" href="{% url 's_admin:s_admin_book_delete' book.pk %}">Delete</a></td>
            </tr>
        {% endfor %}
    </table>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>
{% endblock main %}

s_admin/templates/s_admin/book/s_admin_book_update.html
{% extends "s_admin_base.html" %}
{% load crispy_forms_filters %}
{% block title %}<title>Update book {{ object.name }}</title>{% endblock title %}

{% block main %}
    <div class=container>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-success" value="Update">Update</button>
        </form>
    </div>
{% endblock main %}

s_admin/templates/s_admin/book/s_admin_book_view.html
{% extends "s_admin_base.html" %}
{% block title %}<title>Book {{ object.name }}</title>{% endblock title %}

{% block main %}
    <body>
    <h1>Book: {{ object.name }}</h1>

    <div class="card mb-10" style="max-width: 1850px;">
        <div class="row no-gutters">
            <div class="col-md-5">
                <div class="card-body">
                    <ul class="list-group list-group-flush">

                        <li class="list-group-item">Book name: <b>{{ object.genre }}</b></li>
                        <li class="list-group-item">Cover: <img src="{{ book.cover_photo.url }}" alt="Cover photo" width="100" height="100"></li>
                        <li class="list-group-item">Author: <b>{% for author in book.author.all %}
                            {{ author }}<br>
                        {% endfor %}</b></li>
                        <li class="list-group-item">Series: <b>{{ book.series.title }}</b></li>
                        <li class="list-group-item">Publishing House: <b>{{ book.publishing_house.house }}</b></li>
                        <li class="list-group-item">Genre: <b>{% for genre in book.genre.all %}
                            {{ genre }}<br>
                        {% endfor %}</b></li>
                        <li class="list-group-item">Price: <b>{{ book.price }}</b></li>
                        <li class="list-group-item">Format: <b>{{ book.format }}</b></li>
                        <li class="list-group-item">ISBN: <b>{{ book.isbn_code }}</b></li>
                        <li class="list-group-item">Publishing Date: <b>{{ book.publishing_date }}</b></li>
                        <li class="list-group-item">Pages Amount: <b>{{ book.pages_amount }}</b></li>
                        <li class="list-group-item">Binding: <b>{{ book.binding }}</b></li>
                        <li class="list-group-item">Weight: <b>{{ book.weight }}</b></li>
                        <li class="list-group-item">Amount: <b>{{ book.books_amount }}</b></li>
                        <li class="list-group-item">Age limit: <b>{{ book.age_limit }}</b></li>
                        <li class="list-group-item">Rating: <b>{{ book.rating }}</b></li>
                        <li class="list-group-item">Active: <b>{{ book.is_active }}</b></li>

                    </ul>
                </div>
            </div>
        </div>
    </div>
    <a class="btn btn-success" href="{% url 's_admin:s_admin_book_list' %}">Back </a>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>
    </body>
{% endblock main %}