cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('add/', views.AddBookToCart.as_view(), name='cart_update'),
    path('delete/<int:pk>', views.BookInCartDelete.as_view(), name='book_in_cart_delete'),
    path('', views.CartView.as_view(), name='cart_view')
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'
urlpatterns = [
    path('create/', views.CreateOrder.as_view(), name='create_order'),
    path('update/<int:pk>/', views.CancelOrder.as_view(), name='update_order'),
]

s_admin/urls.py
from django.urls import path
from s_admin import views

app_name = 's_admin'

urlpatterns = [
    path('order/list/', views.SAdminOrderList.as_view(), name='s_admin_order_list'),
    path('order/update/<int:pk>/', views.SAdminOrderUpdate.as_view(), name='s_admin_order_update'),
    path('order/delete/<int:pk>/', views.SAdminOrderDelete.as_view(), name='s_admin_order_delete'),

    path('genre/list/', views.SAdminGenreList.as_view(), name='s_admin_genre_list'),
    path('genre/create/', views.SAdminGenreCreate.as_view(), name='s_admin_genre_create'),
    path('genre/view/<int:pk>/', views.SAdminGenreView.as_view(), name='s_admin_genre_view'),
    path('genre/update/<int:pk>/', views.SAdminGenreUpdate.as_view(), name='s_admin_genre_update'),
    path('genre/delete/<int:pk>/', views.SAdminGenreDelete.as_view(), name='s_admin_genre_delete'),

    path('series/list/', views.SAdminSeriesList.as_view(), name='s_admin_series_list'),
    path('series/create/', views.SAdminSeriesCreate.as_view(), name='s_admin_series_create'),
    path('series/view/<int:pk>/', views.SAdminSeriesView.as_view(), name='s_admin_series_view'),
    path('series/update/<int:pk>/', views.SAdminSeriesUpdate.as_view(), name='s_admin_series_update'),
    path('series/delete/<int:pk>/', views.SAdminSeriesDelete.as_view(), name='s_admin_series_delete'),

    path('author/list/', views.SAdminAuthorList.as_view(), name='s_admin_author_list'),
    path('author/create/', views.SAdminAuthorCreate.as_view(), name='s_admin_author_create'),
    path('author/view/<int:pk>/', views.SAdminAuthorView.as_view(), name='s_admin_author_view'),
    path('author/delete/<int:pk>/', views.SAdminAuthorDelete.as_view(), name='s_admin_author_delete'),
    path('author/update/<int:pk>/', views.SAdminAuthorUpdate.as_view(), name='s_admin_author_update'),

    path('publishing_house/list/', views.SAdminPublishingHouseList.as_view(), name='s_admin_publishing_house_list'),
    path('publishing_house/create/', views.SAdminPublishingHouseCreate.as_view(),
         name='s_admin_publishing_house_create'),
    path('publishing_house/view/<int:pk>/', views.SAdminPublishingHouseView.as_view(),
         name='s_admin_publishing_house_view'),
    path('publishing_house/update/<int:pk>/', views.SAdminPublishingHouseUpdate.as_view(),
         name='s_admin_publishing_house_update'),
    path('publishing_house/delete/<int:pk>/', views.SAdminPublishingHouseDelete.as_view(),
         name='s_admin_publishing_house_delete'),

    path('book/list/', views.SAdminBookList.as_view(), name='s_admin_book_list'),
    path('book/create/', views.SAdminBookCreate.as_view(), name='s_admin_book_create'),
    path('book/delete/<int:pk>/', views.SAdminBookDelete.as_view(), name='s_admin_book_delete'),
    path('book/update/<int:pk>/', views.SAdminBookUpdate.as_view(), name='s_admin_book_update'),
    path('book/view/<int:pk>/', views.SAdminBookView.as_view(), name='s_admin_book_view'),

    path('customer/list/', views.CustomersList.as_view(), name='s_admin_customer_list'),
    path('customer/update/<int:pk>/', views.CustomerUpdate.as_view(), name='s_admin_customer_update'),
    path('customer/view/<int:pk>/', views.CustomerView.as_view(), name='s_admin_customer_view'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from books.views import BookListView, BookView, CreateBook, DeleteBookView, UpdateBook, BookSearch

from references import views
from home_screen.views import TopBooksListView
from my_auth.views import MyLogInView, MyLogOutView, MyPasswordChangeDoneView, MyPasswordChangeView, SignUpView
from cart import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', BookListView.as_view()),
    path('book/search/', BookSearch.as_view(), name='search'),
    path('signin/', MyLogInView.as_view(), name="login"),
    path('logout/', MyLogOutView.as_view(), name='logout'),
    path('password_change/', MyPasswordChangeView.as_view(),
         name='password_change'),
    path('password_change_done/', MyPasswordChangeDoneView.as_view(),
         name='password_change_done'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('profile/', include('my_profile.urls', namespace='profile')),
    path('order/', include('order.urls', namespace='order')),
    path('s_admin/', include('s_admin.urls', namespace='s_admin')),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('book/<int:pk>/', BookView.as_view()),
    path('book/create', CreateBook.as_view()),
    path('book/<int:pk>/update', UpdateBook.as_view()),
    path('book/<int:pk>/delete', DeleteBookView.as_view()),
    path('genre/', views.GenreListView.as_view()),
    path('genre/<int:pk>/', views.GenreView.as_view()),
    path('author/', views.AuthorListView.as_view()),
    path('author/<int:pk>/', views.AuthorView.as_view()),
    path('publishing_house/', views.PublishingHouseListView.as_view()),
    path('publishing_house/<int:pk>/', views.PublishingHouseView.as_view()),
    path('series/', views.SeriesListView.as_view()),
    path('series/<int:pk>/', views.SeriesView.as_view()),
    path('genre/create/', views.CreateGenre.as_view()),
    path('author/create', views.CreateAuthor.as_view()),
    path('series/create', views.CreateSeries.as_view()),
    path('publishing_house/create', views.CreatePublishingHouse.as_view()),
    path('genre/<int:pk>/update', views.UpdateGenre.as_view()),
    path('author/<int:pk>/update', views.UpdateAuthor.as_view()),
    path('series/<int:pk>/update', views.UpdateSeries.as_view()),
    path('publishing_house/<int:pk>/update', views.UpdatePublishingHouse.as_view()),
    path('genre/<int:pk>/delete', views.DeleteGenreView.as_view()),
    path('author/<int:pk>/delete', views.DeleteAuthorView.as_view()),
    path('series/<int:pk>/delete', views.DeleteSeriesView.as_view()),
    path('publishing_house/<int:pk>/delete', views.DeletePublishingHouseView.as_view()),
    path('', TopBooksListView.as_view())
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

order/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from cart.models import Cart
from datetime import datetime


class Order(models.Model):
    cart = models.OneToOneField(
        Cart,
        on_delete=models.PROTECT,
    )

    status1 = models.BooleanField(
        'Cancel Order',
        default=False
    )

    status2 = models.CharField(
        'Status of order',
        choices=(
            ('The order is being processed', 'The order is being processed'),
            ('The order is being delivered', 'The order is being delivered'),
            ('The order was canceled', 'The order was canceled'),
            ('The order is completed', 'The order is completed')
        ),
        max_length=100,
        default='The order is being processed'
    )

    delivery_address = models.CharField(
        'Delivery address',
        max_length=100
    )

    contact_phone = PhoneNumberField(
        'Phone number'
    )

    create = models.DateTimeField(
        default=datetime.now()
    )

    create_date = models.DateField(
        auto_now_add=True
    )

    update_date = models.DateField(
        auto_now=True
    )

    comment = models.TextField(
        'Comment',
        blank=True,
        null=True
    )

    def __str__(self):
        return f"Order #{self.pk}"

s_admin/models.py
from django.db import models

# Create your models here.

order/views.py
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages

from .models import Order
from my_profile.models import Profile
from cart.models import Cart, BookInCart
from books.models import Book


class CreateOrder(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    template_name = 'order/create_order.html'
    model = Order
    fields = ('delivery_address', 'contact_phone', 'comment')
    login_url = reverse_lazy('login')

    def get_object(self, queryset=None):
        user = self.request.user
        user_profile = Profile.objects.get(user=user)

        cart_id = self.request.session.get('cart_id')
        cart = Cart.objects.get(pk=cart_id)
        order_id = self.request.session.get('order_id')

        book_in_cart = BookInCart.objects.all().filter(cart_id=cart_id)

        for book in book_in_cart:
            cur_book = Book.objects.filter(pk=book.book.pk).last()

            new_count = cur_book.books_amount - book.quantity
            if new_count >= 0:
                cur_book.books_amount = new_count
            else:
                book.quantity = cur_book.books_amount
                book.delete()
            cur_book.save()

            if cur_book.books_amount == 0:
                cur_book.is_active = False
                cur_book.save()

        book_in_cart_new = BookInCart.objects.all().filter(cart=cart_id)
        if len(book_in_cart_new) == 0:
            return None

        order = Order.objects.create(cart=cart)
        self.request.session['order_id'] = order.pk

        if user_profile.address1:
            order.delivery_address = user_profile.address1
        if user_profile.phone_number:
            order.contact_phone = user_profile.phone_number
            order.save()
        del self.request.session['cart_id']
        return order

    def get_success_url(self):
        del self.request.session['order_id']
        return reverse_lazy('profile:profile_view')

    def get_success_message(self, cleaned_data):
        message = messages.success(
            f"Your order {self.object} was created successfully. We will call you to confirm the order soon!"
        )
        return message


class CancelOrder(LoginRequiredMixin, UpdateView):
    template_name = 'order/update_order.html'
    model = Order
    fields = ('status1',)
    success_url = reverse_lazy('profile:profile_view')
    login_url = reverse_lazy('login')

    def get_success_url(self):
        order_id = self.request.session.get('order_id')
        order = Order.objects.get(id=order_id)
        if order.status1:
            new_order = Order.objects.filter(pk=order_id).first()
            new_order.status2 = 'The order was canceled'
            new_order.save()
            return reverse_lazy('profile:profile_view')
        else:
            new_order = Order.objects.filter(pk=order_id).first()
            new_order.status2 = 'The order is being processed'
            new_order.save()
            return reverse_lazy('profile:profile_view')

s_admin/templates/s_admin/order/s_admin_order_delete.html
{% extends "s_admin_base.html" %}
{% load crispy_forms_filters %}
{% block title %}<title>Delete Order {{ object.pk }} ???</title>{% endblock title %}
{% block nav_cart %}
    <li class="nav-item">
        <a class="nav-link active" href="{% url 's_admin:s_admin_order_list' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                 stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                 class="feather feather-shopping-cart">
                <circle cx="9" cy="21" r="1"></circle>
                <circle cx="20" cy="21" r="1"></circle>
                <path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path>
            </svg>
            Order List
        </a>
    </li>
{% endblock nav_cart %}
{% block main %}
    <body>
    <h1>Delete Order #{{ object.pk }} ?</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-secondary">Delete</button>
    </form>
{% endblock main %}

s_admin/templates/s_admin/order/s_admin_order_list.html
{% extends "s_admin_base.html" %}
{% block title %} <title>Order List</title> {% endblock title %}

{% load crispy_forms_tags %}
{% block nav_orders %}
    <li class="nav-item">
        <a class="nav-link active" href="{% url 's_admin:s_admin_order_list' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                 stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                 class="feather feather-file">
                <path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path>
                <polyline points="13 2 13 9 20 9"></polyline>
            </svg>
            Orders
        </a>
    </li>
{% endblock nav_orders %}

{% block main %}
    <table class="table table-striped">
        <thead class="thead-dark"></thead>
        <tr>
            <th>Status</th>
            <th>Order</th>
            <th>Customer</th>
            <th>Delivery Address</th>
            <th>Phone Number</th>
            <th>Created</th>
            <th>Price</th>
            <th>Books</th>
        </tr>
        {% for order in object_list %}
            <tr>

                {% if order.status2 == 'The order is being delivered' %}
                    <td><a
                           href="{% url 's_admin:s_admin_order_update' order.pk %}">{{ order.status2 }}</a></td>
                {% elif order.status2 == 'The order is being processed' %}
                    <td><a
                           href="{% url 's_admin:s_admin_order_update' order.pk %}">{{ order.status2 }}</a></td>
                {% elif order.status2 == 'The order was canceled' %}
                    <td><a
                           href="{% url 's_admin:s_admin_order_update' order.pk %}">{{ order.status2 }}</a>
                    </td>
                {% elif order.status2 == 'The order is completed' %}
                    <td><a
                           href="{% url 's_admin:s_admin_order_update' order.pk %}">{{ order.status2 }}</a>
                    </td>
                {% endif %}


                <td><a href="{% url 's_admin:s_admin_order_update' order.pk %}">{{ order.pk }}</a></td>
                {% if order.cart.customer.pk %}
                    <td>
                        <a href="{% url 's_admin:s_admin_customer_view' order.cart.customer.pk%}">{{ order.cart.customer.username }}</a>
                    </td>
                {% else %}
                    <td>Guest</td>
                {% endif %}

                <td>{{ order.delivery_address }}</td>
                <td>{{ order.contact_phone }}</td>
                <td>{{ order.create }}</td>
                <td>
                    {{ order.cart.total_price }} BYN
                </td>
                <td>
                    {% for books in order.cart.books.all %}
                        <a href="{% url 's_admin:s_admin_book_view' books.book.pk %}">{{ books.book }}</a> <br>
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
    </table>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>
{% endblock main %}

s_admin/templates/s_admin/order/s_admin_order_update.html
{% extends "s_admin_base.html" %}
{% load crispy_forms_filters %}
{% block title %}<title>Update {{ object.pk }}</title>{% endblock title %}

{% block main %}
    <div class=container>
        <h3>Info</h3>
        <form action="" method="post" enctype="multipart/form-data">
            <label>User</label>
            <label>
                <input type="text" value="{{ order.cart.customer }}" maxlength="15"
                       class="textinput textInput form-control"
                       disabled>
            </label>
            <label>Price</label>
            <label>
                <input type="text" value="{{ object.cart.total_price }}" maxlength="15"
                       class="textinput textInput form-control" disabled>
            </label>
            <label>Books</label>
            {% for books in object.cart.books.all %}
                <label>
                    <input type="text"
                           value="{{ books.book }}"
                           maxlength="15" class="textinput textInput form-control" disabled>
                </label>


            {% endfor %}
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-success" value="Update">Update</button>
            <a class="btn btn-dark" href="{% url 's_admin:s_admin_order_list' %}"> Back </a>
            <a class="btn btn-danger" href="{% url 's_admin:s_admin_order_delete' order.pk %}">Delete</a>
        </form>

    </div>

{% endblock main %}